SELECT NAME, COUNT(*) AS COUNT_PROJECT
FROM CLIENT
JOIN PROJECT ON CLIENT.ID = PROJECT.CLIENT_ID
GROUP BY NAME
HAVING COUNT(*) = (
  SELECT MAX(COUNT_PROJECT)
  FROM (
    SELECT COUNT(*) AS COUNT_PROJECT
    FROM CLIENT
    JOIN PROJECT ON CLIENT.ID = PROJECT.CLIENT_ID
    GROUP BY NAME
  ) AS subquery
)
