SELECT NAME,BIRTHDAY, 'YOUNGEST' AS TYPE
FROM WORKER
WHERE BIRTHDAY = (
  SELECT MAX(BIRTHDAY),
  FROM WORKER
)
UNION ALL
SELECT NAME,BIRTHDAY, 'ELDEST' AS TYPE
FROM WORKER
WHERE BIRTHDAY = (
  SELECT MIN(BIRTHDAY),
  FROM WORKER
);